name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * 1"}]
  # (optional) Run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/svg/metrics.plugin.activity.svg
          plugin_activity: yes
